USE LabosIKEA;
GO
CREATE TABLE unite(
	id INT PRIMARY KEY NOT NULL IDENTITY,
	libelle VARCHAR(255) NOT NULL
);
GO
CREATE TABLE propriete(
	id INT PRIMARY KEY NOT NULL IDENTITY,
	libelle VARCHAR(255) NOT NULL,
	nom VARCHAR(100) NOT NULL
);
GO
CREATE TABLE produit(
	id INT PRIMARY KEY NOT NULL IDENTITY,
	nom VARCHAR(100) NOT NULL,
	descriptif TEXT NOT NULL,
	prixHT DECIMAL(5,2) NOT NULL,
	Reduction DECIMAL(3,2) NULL
);
GO
CREATE TABLE posseder(
	valeur INT NOT NULL,
	produit_id INT NOT NULL,
	propriete_id INT NOT NULL,
	unite_id INT NULL,
	CONSTRAINT FK_prod_poss FOREIGN KEY(produit_id) REFERENCES produit(id),
	CONSTRAINT FK_prop_poss FOREIGN KEY(propriete_id) REFERENCES propriete(id),
	CONSTRAINT FK_unit_poss FOREIGN KEY(unite_id) REFERENCES unite(id)
);
GO
CREATE TABLE tva(
	id INT PRIMARY KEY NOT NULL IDENTITY,
	taux DECIMAL(3,2) NOT NULL
);
GO
CREATE TABLE lignedevis(
	id INT PRIMARY KEY NOT NULL IDENTITY,
	designation VARCHAR(100) NOT NULL,
	quantite INT NOT NULL,
	pdt_id INT NOT NULL,
	tva_id INT NOT NULL,
	CONSTRAINT FK_PDT_LDEV FOREIGN KEY(pdt_id) REFERENCES produit(id),
	CONSTRAINT FK_TVA_LDEV FOREIGN KEY(tva_id) REFERENCES tva(id)
);
GO
CREATE TABLE codepostal(
	id INT PRIMARY KEY NOT NULL IDENTITY,
	ref CHAR(5) NOT NULL
);
GO
CREATE TABLE ville(
	id INT PRIMARY KEY NOT NULL IDENTITY,
	nom VARCHAR(100) NOT NULL,
	cp_id INT NOT NULL,
	CONSTRAINT FK_CP_VIL FOREIGN KEY(cp_id) REFERENCES codepostal(id)
);
GO
CREATE TABLE adresse(
	id INT PRIMARY KEY NOT NULL IDENTITY,
	adresse1 VARCHAR(150) NOT NULL,
	adresse2 VARCHAR(150) NULL,
	ville_id INT NOT NULL,
	CONSTRAINT FK_VIL_ADR FOREIGN KEY(ville_id) REFERENCES ville(id)
);
GO
CREATE TABLE client(
	id INT PRIMARY KEY NOT NULL IDENTITY,
	nom VARCHAR(100) NOT NULL,
	prenom VARCHAR(100) NOT NULL,
	mail VARCHAR(150) NOT NULL,
	carte BIT NOT NULL,
	adresse_id INT NOT NULL,
	CONSTRAINT FK_ADR_CLI FOREIGN KEY(adresse_id) REFERENCES adresse(id)
);
GO
CREATE TABLE devis(
	id INT PRIMARY KEY NOT NULL IDENTITY,
	date DATE NOT NULL,
	validite DATE NOT NULL,
	titre VARCHAR(100) NOT NULL,
	ldev_id INT NOT NULL,
	client_id INT NOT NULL,
	CONSTRAINT FK_LDEV_DEV FOREIGN KEY(ldev_id) REFERENCES lignedevis(id),
	CONSTRAINT FK_CLI_DEV FOREIGN KEY(client_id) REFERENCES client(id)
);
GO
CREATE TABLE lignefacture(
	id INT PRIMARY KEY NOT NULL IDENTITY,
	designation VARCHAR(100) NOT NULL,
	quantite INT NOT NULL,
	pdt_id INT NOT NULL,
	tva_id INT NOT NULL,
	CONSTRAINT FK_PDT_LFAC FOREIGN KEY(pdt_id) REFERENCES produit(id),
	CONSTRAINT FK_TVA_LFAC FOREIGN KEY(tva_id) REFERENCES tva(id)
);
GO
CREATE TABLE facture(
	id INT PRIMARY KEY NOT NULL IDENTITY,
	date DATE NOT NULL,
	ref CHAR(10) NOT NULL,
	titre VARCHAR(100) NOT NULL,
	lfac_id INT NOT NULL,
	dev_id INT NULL,
	CONSTRAINT FK_DEV_FAC FOREIGN KEY(dev_id) REFERENCES devis(id),
	CONSTRAINT FK_LFAC_FAC FOREIGN KEY(lfac_id) REFERENCES lignefacture(id)
);
GO
CREATE TABLE statut(
	id INT PRIMARY KEY NOT NULL IDENTITY,
	libelle VARCHAR(50) NOT NULL
);
GO
CREATE TABLE paquet(
	id INT PRIMARY KEY NOT NULL IDENTITY,
	ref CHAR(10) NOT NULL,
	libelle VARCHAR(100) NOT NULL,
	poids DECIMAL(6,2) NOT NULL
);
GO
CREATE TABLE colis(
	id INT PRIMARY KEY NOT NULL IDENTITY,
	poids DECIMAL(6,2) NOT NULL,
	paquet_id INT NOT NULL,
	CONSTRAINT FK_PAQ_COL FOREIGN KEY(paquet_id) REFERENCES paquet(id)
);
GO
CREATE TABLE livraison(
	id INT PRIMARY KEY NOT NULL IDENTITY,
	ref CHAR(10) NOT NULL,
	titre VARCHAR(100),
	date DATE NOT NULL,
	adresse_id INT NOT NULL,
	statut_id INT NOT NULL,
	colis_id INT NOT NULL,
	CONSTRAINT FK_ADR_LIV FOREIGN KEY(adresse_id) REFERENCES adresse(id),
	CONSTRAINT FK_STAT_LIV FOREIGN KEY(statut_id) REFERENCES statut(id),
	CONSTRAINT FK_COL_LIV FOREIGN KEY(colis_id) REFERENCES colis(id)
);
GO
CREATE TABLE magasin(
	id INT PRIMARY KEY NOT NULL IDENTITY,
	nom VARCHAR(50) NOT NULL,
	adresse_id INT NOT NULL,
	CONSTRAINT FK_ADR_MAG FOREIGN KEY(adresse_id) REFERENCES adresse(id)
);
GO
CREATE TABLE contrat(
	id INT PRIMARY KEY NOT NULL IDENTITY,
	type VARCHAR(100) NOT NULL
);
GO
CREATE TABLE niveau(
	id INT PRIMARY KEY NOT NULL IDENTITY,
	libelle VARCHAR(50) NOT NULL,
	nom VARCHAR(100) NOT NULL
);
GO
CREATE TABLE typeemploi(
	id INT PRIMARY KEY NOT NULL IDENTITY,
	libelle VARCHAR(50) NOT NULL,
	nom VARCHAR(100) NOT NULL
);
GO
CREATE TABLE personnel(
	id INT PRIMARY KEY NOT NULL IDENTITY,
	nom VARCHAR(100) NOT NULL,
	prenom VARCHAR(100) NOT NULL,
	mail VARCHAR(150) NOT NULL,
	dateembauche DATE NOT NULL,
	adresse_id INT NOT NULL,
	magasin_id INT NOT NULL,
	contrat_id INT NOT NULL,
	niveau_id INT NOT NULL,
	typeemploi_id INT NOT NULL,
	CONSTRAINT FK_ADR_PERS FOREIGN KEY(adresse_id) REFERENCES adresse(id),
	CONSTRAINT FK_MAG_PERS FOREIGN KEY(magasin_id) REFERENCES magasin(id),
	CONSTRAINT FK_CON_PERS FOREIGN KEY(contrat_id) REFERENCES contrat(id),
	CONSTRAINT FK_NIV_PERS FOREIGN KEY(niveau_id) REFERENCES niveau(id),
	CONSTRAINT FK_TEMP_PERS FOREIGN KEY(typeemploi_id) REFERENCES typeemploi(id)
);
GO

CREATE TABLE disponibilite(
	quantite INT NOT NULL,
	allee INT NOT NULL,
	rayon INT NOT NULL,
	produit_id INT NOT NULL,
	magasin_id INT NOT NULL,
	CONSTRAINT FK_PDT_DISP FOREIGN KEY(produit_id) REFERENCES produit(id),
	CONSTRAINT FK_MAG_DISP FOREIGN KEY(magasin_id) REFERENCES magasin(id)
);